
name: Deploy docs

on:
  push:
    branches:
      - 'demo'
    paths:
      - 'docs/**'
  repository_dispatch:
    types: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        with:
          ref: demo
      - run: npm install
      - run: npm install -g ngh 
      - run: sudo ngh  
      - run: export NGH_ACCESS_TOKEN="${{ secrets.GH_TOKEN }}"
      - run: export GH_TOKEN="${{ secrets.GH_TOKEN }}"
      - run: npm run docs:gh-pages
